### PR TITLE
Rename METSWriter to METS

### PR DESCRIPTION
**Pull request by Hwesta**
Rename METSWriter class to METS.

* + Does more than writing (also parses a METS)
* + Reflects what you're actually creating (a METS file)
* - Calling main class METS is too generic and hard to easily grep for (false positives with METS as standard)

Thoughts?

### CODE REVIEW

**Comment by mcantelon** [comment]
This makes sense to me and AFAIK there's no pip-installable "mets" package yet.

**Comment by mistydemeo** [comment]
Works for me; though to bikeshed, maybe `METSDocument` to distinguish from the standard? Don't really have a strong opinion either way.

**Comment by Hwesta** [comment]
I like METSDocument

**Comment by mistydemeo** [comment]
:+1:

**Pull request merged**
