### PR TITLE
Namespace: Update METS namespace to 1.11

### PR DESCRIPTION
**Pull request by Hwesta**

### CODE REVIEW

**Comment by jrwdunham** [comment]
METS "version18" is also hard-coded into MCPClient/lib/clientScripts/createPointerFile.py, MCPClient/lib/clientScripts/createAICMETS.py and MCPClient/lib/clientScripts/archivematicaCreateMETS2.py. Should these be changed to "version111" also?

**Comment by Hwesta** [comment]
See artefactual/archivematica#572 which references to this one. :)

**Comment by jrwdunham** [comment]
Yup. I should probably look at ALL of the PRs for a given ticket before commenting. Thanks!

**Comment by jrwdunham** [comment]
👍

**Comment by Hwesta** [comment]
Since this relates to an Archivematica pull request that depends on an updated metsrw, we'll make a point release with this change so the fix can be incorporated into Archivematica easily.

**Pull request merged**
